server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 201313
    url: jdbc:postgresql://localhost:5432/blogdb
  jpa:
    hibernate:
      ddl-auto: create-drop
